### ISSUE TITLE
Request for good first issue

### ISSUE THREAD

**Issue by RahulDubey391** [tiendc/gofn#33]
Hi @tiendc , 

I hope you are doing well. I found this project fascinating and would like to contribute more. 

Can you raise some potential good first issue so I can start contributing towards them? 

Thanks! ☺

**Comment by tiendc** [comment]
@RahulDubey391 thanks a lot for your offer. I don't have a plan for new features as this lib is made based on the requirements of the projects I've been working on. If you have use case and need more functions, feel free to create `issue` and `pull request`. Adding new UT for complicated functions can also be an option.
